version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: banking_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: banking
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: